# Generated by Django 4.2 on 2026-05-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_height_alter_pokemon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('F', 'Fuego'), ('E', 'Eléctrico'), ('T', 'Tierra'), ('A', 'Agua'), ('L', 'Lagartija')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
