# Generated by Django 4.2 on 2026-05-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_height_alter_pokemon_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('level', models.IntegerField(default=1)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('E', 'Eléctrico'), ('A', 'Agua'), ('L', 'Lagartija'), ('P', 'Planta'), ('T', 'Tierra')], max_length=30),
        ),
    ]
