# Generated by Django 4.2 on 2026-05-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_trainer_alter_pokemon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='age',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('F', 'Fuego'), ('A', 'Agua'), ('L', 'Lagartija'), ('P', 'Planta'), ('T', 'Tierra')], max_length=30),
        ),
    ]
