# Generated by Django 4.2 on 2026-05-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_remove_trainer_age_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('P', 'Planta'), ('L', 'Lagartija'), ('T', 'Tierra'), ('F', 'Fuego'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
