# Generated by Django 4.2 on 2026-05-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('P', 'Planta'), ('L', 'Lagartija'), ('F', 'Fuego'), ('E', 'Eléctrico'), ('A', 'Agua')], max_length=30),
        ),
    ]
