# Generated by Django 4.2 on 2026-05-13 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('L', 'Lagartija'), ('E', 'Eléctrico'), ('P', 'Planta'), ('A', 'Agua'), ('F', 'Fuego')], max_length=30),
        ),
    ]
