# Generated by Django 4.2 on 2026-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0009_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('A', 'Agua'), ('T', 'Tierra'), ('F', 'Fuego'), ('P', 'Planta'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
