# Generated by Django 4.2 on 2026-05-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0010_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('P', 'Planta'), ('E', 'Eléctrico'), ('F', 'Fuego'), ('A', 'Agua'), ('L', 'Lagartija')], max_length=30),
        ),
    ]
