# Generated by Django 4.2 on 2026-06-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0011_pokemon_picture_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('V', 'Volador'), ('L', 'Lagartija'), ('R', 'Roca'), ('P', 'Planta'), ('F', 'Fuego'), ('A', 'Agua'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
