# Generated by Django 4.2 on 2026-07-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0012_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('L', 'Lagartija'), ('V', 'Volador'), ('F', 'Fuego'), ('T', 'Tierra'), ('A', 'Agua'), ('R', 'Roca'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
